/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package cascading.avro.trevni.specified;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ElectricPowerUsage extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
            "{\"type\":\"record\",\"name\":\"ElectricPowerUsage\",\"namespace\":\"cascading.avro.trevni.specified\",\"fields\":[{\"name\":\"addressCode\",\"type\":\"string\"},{\"name\":\"devicePowerEventList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DevicePowerEvent\",\"fields\":[{\"name\":\"power\",\"type\":\"double\"}]}}}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    @Deprecated
    public java.lang.CharSequence addressCode;
    @Deprecated
    public java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> devicePowerEventList;

    /**
     * Default constructor.
     */
    public ElectricPowerUsage() {
    }

    /**
     * All-args constructor.
     */
    public ElectricPowerUsage(java.lang.CharSequence addressCode,
            java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> devicePowerEventList) {
        this.addressCode = addressCode;
        this.devicePowerEventList = devicePowerEventList;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter. Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
        case 0:
            return addressCode;
        case 1:
            return devicePowerEventList;
        default:
            throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader. Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
        case 0:
            addressCode = (java.lang.CharSequence) value$;
            break;
        case 1:
            devicePowerEventList = (java.util.List<cascading.avro.trevni.specified.DevicePowerEvent>) value$;
            break;
        default:
            throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'addressCode' field.
     */
    public java.lang.CharSequence getAddressCode() {
        return addressCode;
    }

    /**
     * Sets the value of the 'addressCode' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setAddressCode(java.lang.CharSequence value) {
        this.addressCode = value;
    }

    /**
     * Gets the value of the 'devicePowerEventList' field.
     */
    public java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> getDevicePowerEventList() {
        return devicePowerEventList;
    }

    /**
     * Sets the value of the 'devicePowerEventList' field.
     * 
     * @param value
     *            the value to set.
     */
    public void setDevicePowerEventList(java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> value) {
        this.devicePowerEventList = value;
    }

    /** Creates a new ElectricPowerUsage RecordBuilder */
    public static cascading.avro.trevni.specified.ElectricPowerUsage.Builder newBuilder() {
        return new cascading.avro.trevni.specified.ElectricPowerUsage.Builder();
    }

    /**
     * Creates a new ElectricPowerUsage RecordBuilder by copying an existing
     * Builder
     */
    public static cascading.avro.trevni.specified.ElectricPowerUsage.Builder newBuilder(
            cascading.avro.trevni.specified.ElectricPowerUsage.Builder other) {
        return new cascading.avro.trevni.specified.ElectricPowerUsage.Builder(other);
    }

    /**
     * Creates a new ElectricPowerUsage RecordBuilder by copying an existing
     * ElectricPowerUsage instance
     */
    public static cascading.avro.trevni.specified.ElectricPowerUsage.Builder newBuilder(
            cascading.avro.trevni.specified.ElectricPowerUsage other) {
        return new cascading.avro.trevni.specified.ElectricPowerUsage.Builder(other);
    }

    /**
     * RecordBuilder for ElectricPowerUsage instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ElectricPowerUsage>
            implements org.apache.avro.data.RecordBuilder<ElectricPowerUsage> {

        private java.lang.CharSequence addressCode;
        private java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> devicePowerEventList;

        /** Creates a new Builder */
        private Builder() {
            super(cascading.avro.trevni.specified.ElectricPowerUsage.SCHEMA$);
        }

        /** Creates a Builder by copying an existing Builder */
        private Builder(cascading.avro.trevni.specified.ElectricPowerUsage.Builder other) {
            super(other);
        }

        /**
         * Creates a Builder by copying an existing ElectricPowerUsage instance
         */
        private Builder(cascading.avro.trevni.specified.ElectricPowerUsage other) {
            super(cascading.avro.trevni.specified.ElectricPowerUsage.SCHEMA$);
            if (isValidValue(fields()[0], other.addressCode)) {
                this.addressCode = data().deepCopy(fields()[0].schema(), other.addressCode);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.devicePowerEventList)) {
                this.devicePowerEventList = data().deepCopy(fields()[1].schema(), other.devicePowerEventList);
                fieldSetFlags()[1] = true;
            }
        }

        /** Gets the value of the 'addressCode' field */
        public java.lang.CharSequence getAddressCode() {
            return addressCode;
        }

        /** Sets the value of the 'addressCode' field */
        public cascading.avro.trevni.specified.ElectricPowerUsage.Builder setAddressCode(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.addressCode = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /** Checks whether the 'addressCode' field has been set */
        public boolean hasAddressCode() {
            return fieldSetFlags()[0];
        }

        /** Clears the value of the 'addressCode' field */
        public cascading.avro.trevni.specified.ElectricPowerUsage.Builder clearAddressCode() {
            addressCode = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /** Gets the value of the 'devicePowerEventList' field */
        public java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> getDevicePowerEventList() {
            return devicePowerEventList;
        }

        /** Sets the value of the 'devicePowerEventList' field */
        public cascading.avro.trevni.specified.ElectricPowerUsage.Builder setDevicePowerEventList(
                java.util.List<cascading.avro.trevni.specified.DevicePowerEvent> value) {
            validate(fields()[1], value);
            this.devicePowerEventList = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /** Checks whether the 'devicePowerEventList' field has been set */
        public boolean hasDevicePowerEventList() {
            return fieldSetFlags()[1];
        }

        /** Clears the value of the 'devicePowerEventList' field */
        public cascading.avro.trevni.specified.ElectricPowerUsage.Builder clearDevicePowerEventList() {
            devicePowerEventList = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        public ElectricPowerUsage build() {
            try {
                ElectricPowerUsage record = new ElectricPowerUsage();
                record.addressCode = fieldSetFlags()[0] ? this.addressCode
                        : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.devicePowerEventList = fieldSetFlags()[1] ? this.devicePowerEventList
                        : (java.util.List<cascading.avro.trevni.specified.DevicePowerEvent>) defaultValue(fields()[1]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}
