/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.maxpoint.cascading.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class md5 extends org.apache.avro.specific.SpecificFixed {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser()
            .parse("{\"type\":\"fixed\",\"name\":\"md5\",\"namespace\":\"com.maxpoint.cascading.avro\",\"size\":16}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /** Creates a new md5 */
    public md5() {
        super();
    }

    /** Creates a new md5 with the given bytes */
    public md5(byte[] bytes) {
        super(bytes);
    }
}
